### ISSUE TITLE
Port to VS Code?

### ISSUE THREAD

**Issue by paulmolluzzo** [ansumanshah/css-in-js#1]
This plugin looks super solid! Any interest in porting it to VS Code? 🙏 🙏 🙏 😄

**Comment by ansumanshah** [comment]
I have not yet used VS Code, will try to check it out and make this work..
PS: Contributions are also welcome :) :)

**Comment by paulmolluzzo** [comment]
[I published an extension for VS Code](https://marketplace.visualstudio.com/items?itemName=paulmolluzzo.convert-css-in-js)!

It's _mostly_ your code except for the actual hook into VS Code. I didn't think a PR made sense since it would mean including both extensions in the distributions for each editor.

I hope you don't mind that I borrowed some of your code. I made sure to credit you in the README and the `convert.js` file. 😄 

Thank you for the inspiration! 🙌
