### ISSUE TITLE
VS Code doesn't build properly

### ISSUE THREAD

**Issue by paulmolluzzo** [ansumanshah/css-in-js#10]
#7, and specifically https://github.com/ansumanshah/css-in-js/pull/7/commits/cba15acb9dd784a5e104cfca3fb00a25dcc44f68, introduced a bug for the build of the VS Code version. The build is now importing a common `css-in-js-helpers` package but it's not being transpiled through babel, throwing errors in the resulting build:

```
Activating extension `paulmolluzzo.convert-css-in-js` failed:  Unexpected token export
Here is the error stack:  /Users/molluzzp/css-in-js-package/packages/vscode-css-in-js/node_modules/css-in-js-helpers/index.js:28
export default function convert(s) {
^^^^^^
SyntaxError: Unexpected token export
```

The two possible solutions are:
1 - symlink the relevant files into the VS Code version and import them directly.
2 - include a transpilation/build step into the `css-in-js-helpers` package.

I'm inclined to go with the second option. @ansumanshah any thoughts or preferences?

**Comment by ansumanshah** [comment]
oops we have to transpile that package with babel yes
