### ISSUE TITLE
Not working in .jsx files

### ISSUE THREAD

**Issue by yohaydy** [ansumanshah/css-in-js#16]
Hi,
Autocomplete is working in .js files, but not in .jsx files ( no suggestion appears ).
Is it possible to make it work in .jsx files as well ?

**Comment by zachgibson** [comment]
Does this work since v1.1.0? PR #21.

**Comment by paulmolluzzo** [comment]
Should work since `v1.1.3`. Versions `1.1.0-1.1.2` were all broken. 😕

**Comment by jsjain** [comment]
I am using the latest version of css-in-js but it doesnt seem to work for me in `javascriptreact` or `typescriptreact` .
