### ISSUE TITLE
command 'extension.convertCSSinJS' not found

### ISSUE THREAD

**Issue by fredbutters** [ansumanshah/css-in-js#22]
WIndows 10
VSCode 1.24.1

I'm getting this when trying to use the keyboard shortcut or when selecting the css and choosing "Convert CSS-In-JS." 

I tried reinstalling and restarting VS Code but it didn't help.

Thanks

**Comment by guruganeshm-prft** [comment]
+1

**Comment by paulmolluzzo** [comment]
Yeah, this is a definite bug, but I'm having trouble even publishing a working fix. I published `v1.1.1` which is a revert back to `1.0.0`, but even that is showing this error.

I don't have much time to look into this, so if anyone can take a stab at it and figure out why this is happening that would be awesome! Sorry I can't get a fix out. For a temporary fix you can package it locally and install the `.vsix`.

Sorry I'm not more help right now. 😞

**Comment by paulmolluzzo** [comment]
Published a fix 2 minutes ago. Please check that it works. 🙏 🙌

**Comment by paulmolluzzo** [comment]
Should be fixed in released `v1.1.3`

**Comment by rishabhrathod01** [comment]
i am trying to debug extension locally and i am facing error  **command 'extension.convertCSSinJS' not found**  i have forked from master also tried using "fix" branch and hadsame issue
