### ISSUE TITLE
css={{...}} prop completion

### ISSUE THREAD

**Issue by threepointone** [ansumanshah/css-in-js#6]
having a great time with this plugin. would you consider supporting `css={{...}}` prop completion as well? this would work for glamor/glamorous/emotion. for reference - https://github.com/threepointone/glamor/blob/master/docs/createElement.md 

happy to pitch in myself if you can point me to what file to hack on. 

thanks again!

**Comment by ansumanshah** [comment]
Thanks a lot for the issue, will be simple I think, hacking on it now.

**Comment by ansumanshah** [comment]
Did a quick fix, have not tested the edge cases but it works 🎉 try updating to v1.4.0

![css-prop](https://user-images.githubusercontent.com/3208863/29997961-af8a7436-903d-11e7-9f8c-7ed95788ecf0.gif)

**Comment by threepointone** [comment]
This looks great!!!
